### PR TITLE
Added popup support

### PR DESCRIPTION
**Pull request by robmarston**
@tabalinas I think you and I have different Git workflows lol. I typically run grunt to compile everything in dist and allow the repo owner to just merge everything into master. If I'm not mistaken you're just looking for changes outside of the dist directory so that you can run grunt yourself? Regardless, this one should just be demo/index.html and src/jssocials/js. If that's not the case just copy the code from my repo and paste it manually, I'm out of ideas haha. Apologies for the inconvenience!

### CODE REVIEW

**Comment by tabalinas** [comment]
Hm, and if you just push all the changes except `dist`? 
I guess you successfully fixed it with previous PR...
Yes, I can put it myself, but then your contribution footprints will be lost J
I would be really glad you to make a PR with two files changed (demo/index.html and jssocials.js).
What do you think? J

**Comment by Ruud68** [comment]
Hi @robmarston and @tabalinas ,
what is the status of this? Still 'under construction'?
Is there something I can do to assist?

**Comment by robmarston** [comment]
I was having trouble merging my code so it never made it in, I can send you what I had if you want to give it a shot.

Sent from my iPhone

On Feb 27, 2016, at 2:58 AM, Ruud <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @robmarston<https://github.com/robmarston> and @tabalinas<https://github.com/tabalinas> ,
what is the status of this? Still 'under construction'?
Is there something I can do to assist?

-

**Comment by Ruud68** [comment]
Here you go #49 did a quick test and.... it works :) thanks @robmarston for the code :)

**Pull request closed without merging**
