### PR TITLE
Changes to the core JS files so that jssocial can use base64 SVGs for the icons too.

### PR DESCRIPTION
**Pull request by CapitalH**
Pull request requested here: https://github.com/tabalinas/jssocials/issues/57#issuecomment-214566145

### CODE REVIEW

**Comment by tabalinas** [comment]
Thank you for the PR.
One thing: could you please exclude `/dist/*` files changes and change only `/src/jssocials.js`?
Thank you in advance!

**Comment by CapitalH** [comment]
I'm sorry, I'm not very good with git, in fact this was my first pull request. If you could point me in the right direction or take care of it yourself would make things much faster for you.

**Comment by tabalinas** [comment]
I believe, It should be straight forward: just revert changes of files in `dist` and push it. 
http://stackoverflow.com/questions/9790448/how-to-update-a-pull-request

**Comment by CapitalH** [comment]
OK, I just cloned the repo on my desktop and reverted the two commits in for the dist folder. Will that do it for you?

**Comment by tabalinas** [comment]
It perfectly makes sense, thank you!

**Comment by CapitalH** [comment]
Your welcome. Glad I could help :)

**Pull request merged**
