### PR TITLE
Popup support

### PR DESCRIPTION
**Pull request by Ruud68**
Hi, okay, found some time to do a 'clean' PR for the popup support PR #37 from @robmarston

### CODE REVIEW

**Comment by Ruud68** [comment]
BTW you can test it here: https://onlinecommunityhub.nl/ :)

**Comment by tabalinas** [comment]
@Ruud68, Thank you for the PR!
I appreciate your efforts on moving the project forward! Thank you!

**Comment by robmarston** [comment]
Yes thank you! I’ll try to figure out why my pull requests aren't working so that I can contribute more in the future :)

On Mar 2, 2016, at 5:29 PM, Artem Tabalin <notifications@github.com<mailto:notifications@github.com>> wrote:


@Ruud68<https://github.com/Ruud68>, Thank you for the PR!
I appreciate your efforts on moving the project forward! Thank you!

**Comment by otterslide** [comment]
Thanks for this feature, I've merged it into my version and it works well.

**Comment by tabalinas** [comment]
Be aware that this functionality was refactored. The option `shareIn` now is available. It accepts any share strategy. Built-in strategeis `self`, `blank`, and `popup`. Will be documented and released very soon (https://github.com/tabalinas/jssocials/commit/61e59097b2444ad37051ef004b202d76e71bf6eb)

**Pull request merged**
