### PR TITLE
added popup support, fixed missing bracket error

### PR DESCRIPTION
**Pull request by robmarston**
I added a popup option that when set to true would open a pop-up window with the share URL instead of a new tab. I tired to follow your naming conventions, formatting, etc. but by all means feel free to improve. I also added some curly brackets where some were missing causing Atom and jshint to complain and the default grunt task not to run without the --force flag. Anyway, thanks for creating the plugin, super easy to use and looks great :)

### CODE REVIEW

**Comment by Ruud68** [comment]
Hi Rob, do you have a website where you have implemented these changes? Would like to test (the easy way: without setting up a test myself :)).
Very curious as to how this will work on mobile devices and different browsers.

**Comment by robmarston** [comment]
I added it to the demo page (at the bottom), I'll put it up on a server momentarily if that's easier -- stand by...

**Comment by robmarston** [comment]
Here's the link: http://stage.robmarston.com/jssocials/demo/. The implementation is at the very bottom. I went back and forth with implementing it at the 'shares' level instead of it being a global option but ended up going with the latter. We could allow further customization of window specs and/or test the user agent for alternative mobile behavior but this basic version worked for the project I used it on so I decided to share it :)

**Comment by Ruud68** [comment]
Hi Rob, tested and works like a charm! Good addition :)
Was worried about the hardcoded window size 500x500px, but on a mobile device it just opens a new tab as it was without the popup window, so the browser handles that perfectly!

Thanks for setting up the test :)
regards,
Ruud.

**Comment by tabalinas** [comment]
Thank you for the PR! 
Could you remove `dist/*` files changes? 
`dist` directory contains files from previous release.

**Comment by robmarston** [comment]
@tabalinas done, apologies for the delay. I haven't ran `grunt` so if you want to generate the updated dist files you may either do it after the merge or let me know and I'll run and commit. Thanks!

**Comment by tabalinas** [comment]
@robmarston, thank you! I like your valuable PR. The only thing, maybe these are latest merging issues, but if you look at changes https://github.com/tabalinas/jssocials/pull/34/files, all new functionality lines are deleted. Any thoughts?

**Comment by robmarston** [comment]
@tabalinas strange, I just ran grunt and commited ... did that fix it? I see my code in there now.

**Comment by tabalinas** [comment]
Looking at file changes I see some all new lines removed: image

Can we fix that?

**Comment by robmarston** [comment]
Reviewing the request took so long I think it spanned over the merging of some other code and somehow the repositories fell out of sync. I'm going to close this request, re-fork master, and add my code back in. Stand by for another (separate) pull request.

**Comment by tabalinas** [comment]
@robmarston Thank you so much! Sorry for the inconvenience.

**Pull request closed without merging**
